name: dorandoran-monitor

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.3
    container_name: doranLogstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ../logs:/logs
    ports:
      - "${LOGSTASH_OUT_PORT}:5044"
    networks:
      - drdr-network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: doranKibana
    environment:
      ELASTICSEARCH_HOSTS: http://doranElasticsearch:9200
    ports:
      - "${KIBANA_OUT_PORT}:5601"
    networks:
      - drdr-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: doranPrometheus
    networks:
      - drdr-network
    ports:
      - "${PROMETHEUS_OUT_PORT}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: doranGrafana
    networks:
      - drdr-network
    ports:
      - "${GRAFANA_OUT_PORT}:3000"
    environment:
      TZ: Asia/Seoul
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

networks:
  drdr-network:
    external: true

volumes:
  grafana-data:
